/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
export const zhCN = {
  ', opens captions settings dialog': ', 开启标题设置弹窗',
  ', opens descriptions settings dialog': ', 开启描述设置弹窗',
  ', opens subtitles settings dialog': ', 开启字幕设置弹窗',
  ', selected': ', 选择',
  'A network error caused the media download to fail part-way.':
    '网络错误导致视频下载中途失败。',
  'Audio Player': '音频播放器',
  'Audio Track': '音轨',
  Background: '背景',
  'Beginning of dialog window. Escape will cancel and close the window.':
    '打开对话窗口。Escape键将取消并关闭对话窗口',
  Black: '黑',
  Blue: '蓝',
  'Caption Settings Dialog': '字幕设定窗口',
  Captions: '内嵌字幕',
  Casual: '舒适',
  Chapters: '节目段落',
  Close: '关闭',
  'Close Modal Dialog': '关闭弹窗',
  'Current Time': '当前时间',
  Cyan: '青',
  Depressed: '压低',
  Descriptions: '描述',
  Done: '完成',
  Dropshadow: '下阴影',
  Duration: '时长',
  'End of dialog window.': '结束对话窗口',
  'Exit Picture-in-Picture': '退出画中画',
  'Font Family': '字体库',
  'Font Size': '字体尺寸',
  Fullscreen: '全屏',
  Green: '绿',
  LIVE: '直播',
  Loaded: '加载完成',
  Magenta: '紫红',
  'Modal Window': '弹窗',
  'Monospace Sans-Serif': '单间隔无细体',
  'Monospace Serif': '单间隔细体',
  Mute: '静音',
  'No compatible source was found for this media.': '无法找到此视频兼容的源。',
  'Non-Fullscreen': '退出全屏',
  None: '无',
  Opaque: '不透明',
  Pause: '暂停',
  'Picture-in-Picture': '画中画',
  Play: '播放',
  'Play Video': '播放视频',
  'Playback Rate': '播放速度',
  Progress: '进度',
  'Progress Bar': '进度条',
  'Proportional Sans-Serif': '比例无细体',
  'Proportional Serif': '比例细体',
  Raised: '浮雕',
  Red: '红',
  'Remaining Time': '剩余时间',
  Replay: '重新播放',
  Reset: '重置',
  Script: '手写体',
  'Seek to live, currently behind live': '尝试直播，当前为延时播放',
  'Seek to live, currently playing live': '尝试直播，当前为实时播放',
  'Semi-Transparent': '半透明',
  'Small Caps': '小型大写字体',
  'Stream Type': '媒体流类型',
  Subtitles: '字幕',
  Text: '文字',
  'Text Edge Style': '字体边缘样式',
  'The media could not be loaded, either because the server or network failed or because the format is not supported.':
    '视频因格式不支持或者服务器或网络的问题无法加载。',
  'The media is encrypted and we do not have the keys to decrypt it.':
    '视频已加密，无法解密。',
  'The media playback was aborted due to a corruption problem or because the media used features your browser did not support.':
    '由于视频文件损坏或是该视频使用了你的浏览器不支持的功能，播放终止。',
  'This is a modal window': '这是一个弹窗',
  'This modal can be closed by pressing the Escape key or activating the close button.':
    '可以按ESC按键或启用关闭按钮来关闭此弹窗。',
  Transparent: '透明',
  Uniform: '均匀',
  Unmute: '取消静音',
  'Video Player': '视频播放器',
  'Volume Level': '音量',
  White: '白',
  Window: '窗口',
  Yellow: '黄',
  'You aborted the media playback': '视频播放被终止',
  'captions off': '关闭内嵌字幕',
  'captions settings': '字幕设定',
  'descriptions off': '关闭描述',
  'descriptions settings': '描述设定',
  'progress bar timing: currentTime={1} duration={2}': '{1}/{2}',
  'restore all settings to the default values': '恢复全部设定至预设值',
  'subtitles off': '关闭字幕',
  'subtitles settings': '字幕设定',
  '{1} is loading.': '正在加载 {1}。',
};
