/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
const localeValues = {
  above: '在上方',
  add: '添加',
  align: '对齐',
  attachment: '附件',
  below: '在下方',
  bgColor: '文本高亮',
  blockTypeToBlockName: {
    bullet: '无序列表',
    check: '任务列表',
    code: '代码块',
    collapsibleContainer: '折叠块',
    h1: '一级标题',
    h2: '二级标题',
    h3: '三级标题',
    h4: '四级标题',
    h5: '五级标题',
    h6: '六级标题',
    number: '有序列表',
    paragraph: '正文',
    quote: '引用',
  },
  bold: '粗体',
  centerAlign: '居中对齐',
  clearCell: '清除单元格',
  clearFormatting: '清除格式',
  column: '列',
  columnHeader: '列标题',
  confirm: '确认',
  deleteColumn: '删除列',
  deleteRow: '删除行',
  deleteTable: '删除表格',
  divider: '分割线',
  equation: '方程',
  excalidraw: '手绘示意图',
  figmaDocument: 'Figma 文档',
  gif: 'GIF动画',
  horizontalRule: '水平线',
  image: '图片',
  indent: '增加缩进',
  indentation: '缩进',
  insert: '插入',
  insertCodeBlock: '插入代码块',
  insertLink: '插入链接',
  insertTable: '插入表格',
  insertTableExperimental: '插入表格（实验性）',
  italic: '斜体',
  justifyAlign: '两端对齐',
  left: '在左边',
  leftAlign: '左对齐',
  link: '链接',
  noofcolumns: '列数',
  noofrows: '行数',
  outdent: '减少缩进',
  poll: '调查',
  redo: '重做',
  remove: '删除',
  right: '在右边',
  rightAlign: '右对齐',
  row: '行',
  rowHeader: '行标头',
  stickyNote: '便签',
  strikethrough: '删除线',
  subscript: '下标',
  superscript: '上标',
  table: '表格',
  tableExperimental: '表格(实验性)',
  textColor: '文字颜色',
  twitter: '推特',
  underline: '下划线',
  undo: '撤销',
  video: '视频',
  youtubeVideo: 'YouTube 视频',
};
export default localeValues;
